INSERT INTO productos (segmento_demo, sku, nombre, marca, precio, moneda, url_origen) VALUES
('libros_ficcion_y_literatura_novelas', '1596652875', 'EL LLANTO DE LOS MUERTOS (LOS CRIMENES DE FJALLBAC', 'Planeta', 49900, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ficcion_y_literatura_novelas', '1600349046', 'EL CANTO INVISIBLE', 'Alfaguara', 44999, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_humanidades_biografias_y_relatos', '1592243483', 'EL CANTO DEL CISNE', 'Plaza & Janes', 44999, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_infantil_y_juvenil_jovenes_lectores', '1550251455', 'UNA CORTE DE ARMONIA ROTA', 'Planeta', 36900, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_esoterismo_astrologia', '1598840203', 'HOROSCOPO CHINO 2027', 'Ediciones B', 34999, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ficcion_y_literatura_novelas', '1597286924', 'LAS MALAS', 'Big Sur', 54000, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ficcion_y_literatura_novelas', '1597286855', 'LA VIDA QUE IMPORTA', 'Planeta', 44900, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ficcion_y_literatura_novelas', '1592842599', 'LA MARCA DEL PSICOPATA', 'Motus', 37500, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ficcion_y_literatura_novelas', '1600349020', 'UN DIA EN LA VIDA DE CLARITA', 'Alfaguara', 37999, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ficcion_y_literatura_novelas', '1596652848', 'MADAME BORGES', 'Planeta', 39900, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ficcion_y_literatura_novelas', '1598839892', 'UNA FAMILIA MODERNA', 'Plaza & Janes', 49999, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_infantil_y_juvenil_entretenimientos', '1600349165', 'NUEVA ENCICLOPEDIA POKEMON', 'Montena', 54999, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ficcion_y_literatura_novelas', '1596652936', 'MAMA ESTA DORMIDA', 'Planeta', 39900, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ficcion_y_literatura_novelas', '1598840048', 'MIENTRAS ESPERO', 'Suma De Letras', 34999, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ficcion_y_literatura_novelas', '1580448471', 'PROMESA DE SANGRE', 'Editorial El Ateneo', 34900, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ficcion_y_literatura_novelas', '1577405960', 'LA INQUILINA', 'Suma De Letras', 45999, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ficcion_y_literatura_comic_s_novela_grafica', '1578966678', 'LLAMAME POR TU NOMBRE', 'V & R Editoras', 36000, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_infantil_y_juvenil_cuentos', '1595384534', 'ATRAPADOS EN EL CIRCO ENCANTADO', 'Capicua', 27000, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ficcion_y_literatura_novelas', '1577406010', 'EL DESAFIO FINAL', 'Ediciones B', 44999, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_autoayuda_maternidad', '1483686597', 'ALBUM DE NUESTRO PRIMER ENCUENTRO', 'Albatros - Crianza Y Vinculos', 45000, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ficcion_y_literatura_novelas', '1577405986', 'LAS IRACUNDAS', 'Random House', 35499, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_autoayuda_superacion_personal', '1580448398', 'VIVE TU ASCENDENTE', 'Editorial El Ateneo', 25900, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_computacion_y_sistemas_videojuegos', '1589992091', 'ROBLOX', 'Az Editora', 19000, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ficcion_y_literatura_novelas', '1558417620', 'EL DIA DE LA TRILLA - EMPIREO 4 - EDICION LIMITADA CON CANTOS TINTADOS', 'Planeta', 59990, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ficcion_y_literatura_ciencia_ficcion_fantastica', '1577405837', 'EL TALISMAN - EL TALISMAN 1', 'Plaza & Janes', 61999, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ciencias_de_la_salud_naturales_y_divulgacion_cientifica_psicologia', '1579152759', 'UNA BUENA VIDA', 'Planeta', 38900, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ficcion_y_literatura_novelas', '1577405785', 'CASA NEGRA - EL TALISMAN 2', 'Plaza & Janes', 61999, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ficcion_y_literatura_novelas', '1579152687', 'MALDITA', 'Planeta', 39900, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_derecho_y_ciencias_sociales_historia', '1580448235', 'ROZAS', 'Editorial El Ateneo', 21900, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_derecho_y_ciencias_sociales_historia', '1580745677', 'ESO NO ESTABA EN MI LIBRO DE HISTORIA DE LA ALQUIMIA', 'Ediciones Lea', 38000, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_negocios_y_cs_economicas_administracion', '1580745075', 'CHANGE ADOPTION INNOVATION', 'Ediciones Lea', 28000, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_infantil_y_juvenil_novela', '1578966452', 'WONDERF', 'Vrya', 40000, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_derecho_y_ciencias_sociales_derecho', '1587795030', 'HIGIENE Y SEGURIDAD EN EL TRABAJO 3.1', 'Errepar', 20900, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_infantil_y_juvenil_jovenes_lectores', '1577405624', 'MODELO A SEGUIR (GAME CHANGERS 5)', 'Montena', 33299, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_ciencias_de_la_salud_naturales_y_divulgacion_cientifica_divulgacion_cientifica', '1590528070', 'EL PAIS DE LA CIENCIA', 'Az Editora', 35000, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_juegos_deportes_y_recreacion_deportes', '1573022427', 'ARRIBA, MESSI - CINEBOOK', 'Catapulta', 11900, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_autoayuda_superacion_personal', '1580448315', 'LIDERAZGO CON PROPOSITO', 'Editorial El Ateneo', 29500, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_humanidades_sociologia', '1577530957', 'EL LIBRO NEGRO DE LA NUEVA DERECHA', 'Siglo Xxi Editores Argentina', 31900, 'ARS', 'yenny-elateneo.com (home, pagina guardada)'),
('libros_derecho_y_ciencias_sociales_politica', '1581022028', 'QUE DIABLOS NOS PASO?', 'Sudamericana', 39999, 'ARS', 'yenny-elateneo.com (home, pagina guardada)')
ON CONFLICT (sku) DO NOTHING;