-- Tabla de sucursales Yenny - El Ateneo (fuente: listado interno del cliente)
CREATE TABLE IF NOT EXISTS sucursales (
    id SERIAL PRIMARY KEY,
    nombre TEXT NOT NULL,
    regional TEXT NOT NULL,
    responsable_regional TEXT
);

INSERT INTO sucursales (nombre, regional, responsable_regional) VALUES
('Aeroparque', 'Regional 1', 'Rolando, Adriana'),
('Alto Noa Shopping - Salta', 'Regional 1', 'Rolando, Adriana'),
('Ateneo Tucuman', 'Regional 1', 'Rolando, Adriana'),
('Dot Baires Shopping', 'Regional 1', 'Rolando, Adriana'),
('Ezeiza', 'Regional 1', 'Rolando, Adriana'),
('Feria Itinerante Region 1', 'Regional 1', 'Rolando, Adriana'),
('Jujuy', 'Regional 1', 'Rolando, Adriana'),
('Palmas del Pilar', 'Regional 1', 'Rolando, Adriana'),
('Plaza Oeste', 'Regional 1', 'Rolando, Adriana'),
('Salta Centro', 'Regional 1', 'Rolando, Adriana'),
('San Justo', 'Regional 1', 'Rolando, Adriana'),
('Solar de la Abadia', 'Regional 1', 'Rolando, Adriana'),
('Tortugas Open Mall', 'Regional 1', 'Rolando, Adriana'),
('Tucuman Portal', 'Regional 1', 'Rolando, Adriana'),
('Unicenter', 'Regional 1', 'Rolando, Adriana'),
('Villa Urquiza', 'Regional 1', 'Rolando, Adriana'),

('Abasto', 'Regional 2', 'Ferrari, Pablo'),
('Alto Palermo', 'Regional 2', 'Ferrari, Pablo'),
('Ateneo Cordoba Centro', 'Regional 2', 'Ferrari, Pablo'),
('Mendoza Centro', 'Regional 2', 'Ferrari, Pablo'),
('Mendoza Palmares', 'Regional 2', 'Ferrari, Pablo'),
('Mendoza Shopping', 'Regional 2', 'Ferrari, Pablo'),
('Nuevo Centro Shopping', 'Regional 2', 'Ferrari, Pablo'),
('Palermo Portal', 'Regional 2', 'Ferrari, Pablo'),
('Paseo Alcorta', 'Regional 2', 'Ferrari, Pablo'),
('Patio Bullrich', 'Regional 2', 'Ferrari, Pablo'),
('Patio Olmos', 'Regional 2', 'Ferrari, Pablo'),
('Rio Cuarto', 'Regional 2', 'Ferrari, Pablo'),
('San Luis', 'Regional 2', 'Ferrari, Pablo'),
('Villa Crespo', 'Regional 2', 'Ferrari, Pablo'),

('Alto Comahue', 'Regional 3', 'Sueyro, Sergio'),
('Ateneo Juramento', 'Regional 3', 'Sueyro, Sergio'),
('Ateneo La Plata', 'Regional 3', 'Sueyro, Sergio'),
('Avellaneda', 'Regional 3', 'Sueyro, Sergio'),
('Bahia Blanca Shopping', 'Regional 3', 'Sueyro, Sergio'),
('Bariloche', 'Regional 3', 'Sueyro, Sergio'),
('Calle 12', 'Regional 3', 'Sueyro, Sergio'),
('Feria Itinerante N1 - Region 3', 'Regional 3', 'Sueyro, Sergio'),
('Feria Itinerante N2 - Region 3', 'Regional 3', 'Sueyro, Sergio'),
('La Plata', 'Regional 3', 'Sueyro, Sergio'),
('Lomas de Zamora', 'Regional 3', 'Sueyro, Sergio'),
('Mar del Plata Los Gallegos', 'Regional 3', 'Sueyro, Sergio'),
('Mar del Plata M. Benou', 'Regional 3', 'Sueyro, Sergio'),
('Mar del Plata Paseo Aldrey', 'Regional 3', 'Sueyro, Sergio'),
('Neuquen Portal Patagonia', 'Regional 3', 'Sueyro, Sergio'),
('Quilmes Centro', 'Regional 3', 'Sueyro, Sergio'),
('Trelew', 'Regional 3', 'Sueyro, Sergio'),

('Alto Rosario', 'Regional 4', 'Benderschi, Federico'),
('Ateneo Florida 340', 'Regional 4', 'Benderschi, Federico'),
('Ateneo Florida 632', 'Regional 4', 'Benderschi, Federico'),
('Ateneo Rosario', 'Regional 4', 'Benderschi, Federico'),
('Borges', 'Regional 4', 'Benderschi, Federico'),
('Caballito', 'Regional 4', 'Benderschi, Federico'),
('Corrientes Shopping', 'Regional 4', 'Benderschi, Federico'),
('Devoto', 'Regional 4', 'Benderschi, Federico'),
('Flores', 'Regional 4', 'Benderschi, Federico'),
('Parana', 'Regional 4', 'Benderschi, Federico'),
('Remeros (Nordelta)', 'Regional 4', 'Benderschi, Federico'),
('Resistencia', 'Regional 4', 'Benderschi, Federico'),
('Rosario Portal', 'Regional 4', 'Benderschi, Federico'),
('San Miguel', 'Regional 4', 'Benderschi, Federico'),
('Santa Fe Ribera Shopping', 'Regional 4', 'Benderschi, Federico'),

('Ateneo Grand Splendid', 'Regional 5', NULL),
('Experiencia G. Splendid (Suc)', 'Regional 5', NULL),
('Experiencia Grand Splendid', 'Regional 5', NULL);
